//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrbitStore.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdentityBinderDirectory
    {
        public int IdentityId { get; set; }
        public string IdentityName { get; set; }
        public bool IdentityActive { get; set; }
        public int BinderId { get; set; }
        public string BinderName { get; set; }
        public string BinderPath { get; set; }
        public bool BinderActive { get; set; }
        public string LinkName { get; set; }
        public string LinkPath { get; set; }
        public bool LinkActive { get; set; }
        public string DirectoryPath { get; set; }
    }
}
