//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrbitStore.Web.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OrbitStoreEntities : DbContext
    {
        public OrbitStoreEntities()
            : base("name=OrbitStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Binder> Binder { get; set; }
        public virtual DbSet<BinderHistory> BinderHistory { get; set; }
        public virtual DbSet<BinderResourceLink> BinderResourceLink { get; set; }
        public virtual DbSet<BinderResourceLinkHistory> BinderResourceLinkHistory { get; set; }
        public virtual DbSet<Identity> Identity { get; set; }
        public virtual DbSet<IdentityBinderLink> IdentityBinderLink { get; set; }
        public virtual DbSet<IdentityBinderLinkHistory> IdentityBinderLinkHistory { get; set; }
        public virtual DbSet<IdentityHistory> IdentityHistory { get; set; }
        public virtual DbSet<LinkType> LinkType { get; set; }
        public virtual DbSet<LinkTypeHistory> LinkTypeHistory { get; set; }
        public virtual DbSet<Organization> Organization { get; set; }
        public virtual DbSet<OrganizationHistory> OrganizationHistory { get; set; }
        public virtual DbSet<OrganizationIdentityLink> OrganizationIdentityLink { get; set; }
        public virtual DbSet<OrganizationIdentityLinkHistory> OrganizationIdentityLinkHistory { get; set; }
        public virtual DbSet<Resource> Resource { get; set; }
        public virtual DbSet<ResourceHistory> ResourceHistory { get; set; }
        public virtual DbSet<BinderResourceDirectory> BinderResourceDirectory { get; set; }
        public virtual DbSet<IdentityBinderDirectory> IdentityBinderDirectory { get; set; }
        public virtual DbSet<OrganizationIdentityDirectory> OrganizationIdentityDirectory { get; set; }
    }
}
